### PR TITLE
Factory work

### LINKED ISSUE #92: Consistent Factory Usage
We use one set of factories in binning-utilities and tile-service, another in tile-generation.  We need to settle on one, and use it consistently.

### LINKED ISSUE #121: Value Transformer Construction
Presently a monolithic factory, Value Transformer construction should be converted to using UberFactories.

### PR DESCRIPTION
**Pull request by nkronenfeld**
Break factory code out into its own project.
Update the new index- and value- extractor code to use factories properly.
Create factories for binning analytics, and update the value-extractor code to use a binning analytic factory - so now we have access to all the numeric binning analytics on all standard value extractors.

Partially fixes #92
Gives up on #91

### CODE REVIEW

**Comment by cdbethune** [comment]
Minor points aside, this seems to line up with what we've discussed.  I'll merge once the conflicts are out.

**Comment by nkronenfeld** [comment]
Regarding guava: I believe we need that to resolve a version conflict between two guava versions imported by other projects, but I'm not sure.  I'll try and check tile-generation and tile-service.

**Comment by nkronenfeld** [comment]
mean vs. average - I intentionally put in both.  The old code accepted both, I was trying to replace functionality without change.

**Comment by nkronenfeld** [comment]
Should be all set now.
I think you were right about Guava

**Pull request merged**
