### PR TITLE
Fixes value transformers use of range minimums

### LINKED ISSUE #71: Tile color rendering incorrectly maps mins/maxes when min bin is non-zero
Specifically regarding [these two lines](https://github.com/oculusinfo/aperture-tiles/blob/develop/tile-service/src/main/java/com/oculusinfo/tile/rendering/impl/DoublesImageRenderer.java#L108-L109) in `DoublesImageRenderer`

If the min bin value is 0 the color ramp range is mapped correctly. If the min bin value is non-zero the min/max range against which values are transformed into colors is incorrect because it assumes a 0 minimum. The problem becomes more confusing (to the end user) if the rangeMin is set > 0. I believe the lines in question should read:

```java
double scaledLevelMinFreq = t.transform(minimumValue) + (t.transform(maximumValue)-t.transform(minimumValue))*rangeMin/100;
double scaledLevelMaxFreq = t.transform(minimumValue) + (t.transform(maximumValue)-t.transform(minimumValue))*rangeMax/100;
```

This is most apparent when bin values range into negative numbers.

### PR DESCRIPTION
**Pull request by robharper**
Both the linear and log10 transformers did not properly handle minimum layer values - linear assumed a 0 minimum and log assumed a 1 minimum. This PR fixes both and allows any arbitrary minimum values to be used. This is important for layers whose data is within a range say of [100,200] so that the [0,100) range isn't eating up a bunch of the color space by default. It is also important for datasets that range into negative numbers so all negative values are assigned colors (vs transparent due to less than assumed min).

This PR also adds support to the log transformer to handle small numbers close to (and equal to) zero by clamping them to zero. It also allows the log transformer to handle ranges that span zero using the technique applied here: https://github.com/oculusinfo/aperturejs/blob/develop/aperture-client/src/main/javascript/core-classes/Range.js#L1014

Fixes #71

### CODE REVIEW

**Comment by nkronenfeld** [comment]
Logs of negative numbers make no sense.

There are plenty of alternative scales that do for situations like the ones in question - sigmoid (which we already have), cube root, or arcsinh, to name 3 - that I don't think we really need to resort to mathematical nonsense.

**Comment by robharper** [comment]
The purpose of this code isn't to represent data for mathematical plotting purposes. When we have data that contains negative and positive values (say profits and losses) we may want to use a polar color ramp (red -> neutral -> green). We can map values linearly but often we'll want a scale that looks more like this:

```
   |          |           |         |         |          |            |
-1000        -100        -10        0         10        100        -1000
```

We can achieve this by using the log of the magnitude. If our input values are always integers this works nicely and is totally reasonable. The benefit of log over the other suggested functions is that it equally spaces factors of 10 where the others do not.

**Comment by robharper** [comment]
See also http://aperturejs.com/api/js/symbols/aperture.Scalar.html#logarithmic

**Comment by nkronenfeld** [comment]
I understand the point, but think it's misrepresentative and confusing, and can easily be accidentally misused to show information that is patently false (one can argue it does so all the time, by definition).

I do not agree that such a scale is reasonable.

The only argument I see in favor of this approach is the visual scale.  However, we don't actually ever display such a scale, so the evenness is irrelevant.  We don't display these on an axis.  We could, in fact, use any of these alternative, mathematically sound scales, and set the scaling to show different colors at each power of 10, to entirely the same effect, and achieve all you want in terms of scaling of visibility, without the inherent mathematical inconsistencies of this approach.

There are assumptions one can make about the data that minimize the irrelevance and mathematical inconsistencies - but we have no way of enforcing those assumptions, or even knowing if they apply.

**Comment by nkronenfeld** [comment]
Besides the log issue, I see nothing in here that makes anything worse.  The rendering code is full of magic numbers with no explanation (which is probably my fault), and I have little confidence in it from reading it, but that's not the fault of this PR - this PR I think takes several steps in the right direction.

**Comment by robharper** [comment]
I think it's important to distinguish between the mathematical function (log) and the intended purpose of this feature - facilitating visual comprehension of a range of numbers when mapped to color. Remember that the output of this transform isn't plotted on a continuous line graph but is used to choose a color from a palette so discontinuity around zero isn't so important.

If we left log as a pure mathematical log function and let it fail for 0 and negative numbers it would put the onus on the user to know better (and to know their data has the odd zero or -ve which could be hidden by letting log fail in these cases). We'd say "you should be using arcsinh instead" but the user is probably thinking "I just want to see color mapped to order of magnitude, negative or otherwise".

So what if we abandon pure mathematical naming and behavior and name the transforms based on application. Rename this enhanced log transformer that handles zeros and negatives to "OrderOfMagnitudeValueTransformer". If there's a need for a pure log10 we can add it later.

**Comment by nkronenfeld** [comment]
"Order of Magnitude" has the same issue - that -5 already has a meaning.

"Remember that the output of this transform isn't plotted on a continuous line graph but is used to choose a color from a palette so discontinuity around zero isn't so important." - this also means there's no importance to doing this as a log, and using a sigmoid, which has mathematical validity too, would work just as well.

Also, using a sigmoid, there are easy ways to separate the range into 4 sections, instead of 2, and have a visual indication of outlier vs. central values.

**Comment by cdbethune** [comment]
We have a number of mathematically correct functions available out of the box, so having a log transformer that behaves as one would expect keep things consistent.  That said, the specialized log-ish function that is being proposed addresses an issue that has been encountered a few times already, and it sounds like it has worked fairly well in Aperture JS.  So, leave the log transformer as is, and add the new order of magnitude transformer.

**Comment by robharper** [comment]
Re a pure log transformer (or any transformer for that matter) how should error cases be handled? Prior to this PR the transformer would return Infinity. The implied contract of transformers is that the output should be in [0,1].

**Comment by robharper** [comment]
Reverted to basic log with catch to not bail on minimums <= 0

**Pull request merged**
