### PR TITLE
Separate Avro tile implementations for dense and sparse data storage.

### PR DESCRIPTION
**Pull request by nkronenfeld**
Rename the old TileData to DenseTileData
Pull out a TileData interface
Implement a SparseTileData
Make it all work.
Make the various tiling jobs properly choose between the two.
Partially addresses #126

### CODE REVIEW

**Comment by nkronenfeld** [comment]
Hm, may need to do something with line binner still.

**Comment by cdbethune** [comment]
Did you end up looking at the size of a compressed dense tile vs a compressed sparse tile?  I would just be curious to see how far apart they land.

**Comment by nkronenfeld** [comment]
I did not.  Given compression, I wouldn't expect the disk storage to really be all that different though.
I would expect to see differences in read and write times, and I would expect to see different memory usage in an active application.

But I can check.

**Comment by nkronenfeld** [comment]
Don't merge - a bit more merge work, I have to fix Rob's TileDataView

**Pull request merged**
